#!/usr/bin/env python3
"""Build VRML 3D models for the three parts KiCad has no model for.

CARD1, USB1 and LED1 render as nothing in the 3D viewer, because their
footprints are generated by gen_footprints.py and nothing off the shelf fits:

  * KiCad carries six full-size SD socket footprints but no 3D model for any of
    them, and none match the SD-006M. Connector_Card.3dshapes holds microSD and
    nanoSIM only.
  * Connector_USB has USB-A receptacles, not a board-mounted male plug.
  * The LED is an Everlight 0804 (2.0 x 1.0 mm), a size outside the metric
    chip series entirely, which is also why its land had to be part-specific.

These are honest envelopes, not CAD. Every dimension below is taken from the
manufacturers' drawings and noted with its source; curves, chamfers, the
push-push mechanism and the shell's rolled seams are all omitted. Good enough
to see what sits where and to eyeball clearance. Not a substitute for a real
STEP model if you ever need a mechanical assembly check.

Units and axes, both of which are easy to get wrong:
  * KiCad VRML is authored in 0.1 inch. Every mm figure here is divided by
    2.54 on the way out, so the footprint's model entry needs scale 1 1 1.
  * Footprint Y is positive downward; VRML Y is positive up. Y is negated.
  * Z is height above the board surface.

    ./tools/gen_3dmodels.py         # writes hardware/sd-net.3dshapes/
"""

import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "hardware", "sd-net.3dshapes")
VRML_UNIT = 2.54          # mm per VRML unit, KiCad's convention

# name: (diffuse, specular, shininess)
MATERIALS = {
    "steel":   ((0.72, 0.73, 0.75), (0.55, 0.55, 0.57), 0.55),
    "nickel":  ((0.78, 0.79, 0.80), (0.60, 0.60, 0.62), 0.65),
    "plastic": ((0.14, 0.14, 0.15), (0.05, 0.05, 0.05), 0.15),
    "cavity":  ((0.08, 0.08, 0.09), (0.02, 0.02, 0.02), 0.05),
    "led":     ((0.55, 0.82, 0.32), (0.35, 0.45, 0.30), 0.75),
}


def box(x0, x1, y0, y1, z0, z1, material):
    """A box given footprint-frame mm bounds. y0/y1 are footprint Y (down +)."""
    cx, cy, cz = (x0 + x1) / 2, -(y0 + y1) / 2, (z0 + z1) / 2
    sx, sy, sz = abs(x1 - x0), abs(y1 - y0), abs(z1 - z0)
    (dr, dg, db), (sr, sg, sb), sh = MATERIALS[material]
    u = VRML_UNIT
    return (f"Transform {{\n"
            f"  translation {cx/u:.6f} {cy/u:.6f} {cz/u:.6f}\n"
            f"  children [\n"
            f"    Shape {{\n"
            f"      appearance Appearance {{ material Material {{\n"
            f"        diffuseColor {dr} {dg} {db}\n"
            f"        specularColor {sr} {sg} {sb}\n"
            f"        shininess {sh}\n"
            f"      }} }}\n"
            f"      geometry Box {{ size {sx/u:.6f} {sy/u:.6f} {sz/u:.6f} }}\n"
            f"    }}\n"
            f"  ]\n"
            f"}}\n")


def write(name, header, shapes):
    os.makedirs(OUT, exist_ok=True)
    body = "#VRML V2.0 utf8\n" + "".join(f"# {l}\n" for l in header.strip().split("\n"))
    body += "\n" + "\n".join(shapes)
    open(os.path.join(OUT, name + ".wrl"), "w").write(body)
    print(f"{name}.wrl  ({len(shapes)} solid{'s' if len(shapes) != 1 else ''})")


def sd_006m():
    # SOFNG SD-006M, datasheet page 1: body 29.0 L x 28.5 W x 2.9 H.
    # Placement in the footprint frame comes off the page 2 land pattern:
    # contacts at y = -11.524, pegs at y = +13.076, and the card-entry end a
    # further 5.5 beyond the pegs -> y = +18.576. A 29.0 mm body ending there
    # starts at y = -10.424, which leaves the contact tails protruding ~1.1 mm
    # behind the housing. That is what the drawing shows.
    W, H = 28.5, 2.9
    y_back, y_front = -10.424, 18.576
    shapes = [box(-W / 2, W / 2, y_back, y_front, 0.0, H, "steel")]
    # Card slot mouth, so the front face reads as an opening rather than a
    # solid block. 24.2 wide is the card width the socket accepts.
    shapes.append(box(-12.1, 12.1, y_front - 1.2, y_front, 0.55, 2.45, "cavity"))
    write("SD-006M", """
        SOFNG SD-006M full-size SD socket, LCSC C125615.
        Envelope from the datasheet: 29.0 L x 28.5 W x 2.9 H, positioned from
        the page 2 land pattern. Push-push mechanism and shell detail omitted.
        """, shapes)


def usb_am90():
    # Shou Han AM90, drawing A/0 2018.07.10. Plastic housing 12.52 wide and
    # 5.85 tall (front view); metal shell 12.00 x 4.50, the USB-A standard.
    # Overall length 19.85, split here as a 7.00 housing plus a 12.85 shell.
    # The plug projects in +Y, away from the pin row and out past the board
    # edge, which sits 4.58 mm from this footprint's origin.
    shapes = [box(-6.26, 6.26, -2.30, 4.70, 0.0, 5.85, "plastic")]
    # Shell, vertically centred on the housing.
    shapes.append(box(-6.00, 6.00, 4.70, 17.55, 0.675, 5.175, "nickel"))
    # The moulded insulator visible inside the shell mouth.
    shapes.append(box(-5.00, 5.00, 15.55, 17.55, 1.2, 3.0, "cavity"))
    write("USB-AM90", """
        Shou Han AM90 right-angle USB-A male plug, LCSC C404965.
        Housing 12.52 x 5.85 and shell 12.00 x 4.50 from the drawing; overall
        19.85 long. Contacts, latching dimples and shell seams omitted.
        """, shapes)


def led():
    # Everlight 12-215SYGC/S530-E2, LCSC C131283. An 0804: 2.0 x 1.0 mm body,
    # ~0.8 mm tall. Centred on the footprint origin, matching the land.
    shapes = [box(-1.0, 1.0, -0.5, 0.5, 0.0, 0.8, "led")]
    write("LED-12-215SYGC", """
        Everlight 12-215SYGC/S530-E2/TR8 yellow-green chip LED, LCSC C131283.
        0804 body, 2.0 x 1.0 x 0.8 mm. Lens curvature omitted.
        """, shapes)


def main():
    sd_006m()
    usb_am90()
    led()
    print(f"-> {os.path.relpath(OUT, HERE)}/")


if __name__ == "__main__":
    main()
