#!/usr/bin/env python3
"""Check the rev 2.0 KiCad netlist against intent, and diff it against rev 1.5.

Two questions this answers:

1. Does the schematic actually carry the netlist we meant to build? (Compared
   against the NETS table in gen_schematic.py.)
2. Is the *only* difference from the fabricated rev 1.5 board the intended
   power-rail split? Anything else is damage.

    ./tools/verify_netlist.py [netlist.net]

Generate the input with:
    kicad-cli sch export netlist --format kicadsexpr -o build/sd-net.net \\
        hardware/sd-net.kicad_sch
"""

import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_schematic import NETS, sexp_parse  # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KICAD_CLI = "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"
SCH = os.path.join(HERE, "hardware", "sd-net.kicad_sch")

# Rev 1.5 as fabricated, recovered by tools/altium_netlist.py. Net names are the
# EasyEDA autogenerated ones; only the membership matters here.
REV15 = {
    "$1N2351": {("C1", "1"), ("C2", "1"), ("C3", "1"), ("C4", "1"), ("C5", "1"),
                ("C6", "1"), ("CARD1", "4"), ("R1", "1"), ("U1", "13"),
                ("U1", "8"), ("U1", "9")},
    "$1N2347": {("U1", "10"), ("USB1", "1")},
    "GND":     {("C1", "2"), ("C2", "2"), ("C3", "2"), ("C4", "2"), ("C5", "2"),
                ("C6", "2"), ("CARD1", "3"), ("CARD1", "6"), ("U1", "1"),
                ("U1", "14"), ("USB1", "4")},
    "$1N2355": {("CARD1", "2"), ("U1", "5")},
    "$1N2358": {("CARD1", "5"), ("U1", "4")},
    "$1N2360": {("CARD1", "7"), ("U1", "3")},
    "$1N2361": {("CARD1", "8"), ("U1", "2")},
    "$1N2362": {("CARD1", "9"), ("U1", "7")},
    "$1N2356": {("CARD1", "1"), ("U1", "6")},
    "$1N3940": {("U1", "15"), ("USB1", "3")},
    "$1N3946": {("U1", "16"), ("USB1", "2")},
    "$1N2352": {("LED1", "2"), ("R1", "2")},
    "$1N2353": {("LED1", "1"), ("U1", "12")},
}


def find(node, key):
    return [c for c in node if isinstance(c, list) and c and c[0] == key]


def first_val(node, key):
    hits = find(node, key)
    return hits[0][1].strip('"') if hits and len(hits[0]) > 1 else None


def parse_netlist(path):
    root = sexp_parse(open(path).read())
    nets = {}
    for netsec in find(root, "nets"):
        for net in find(netsec, "net"):
            name = (first_val(net, "name") or "").lstrip("/")
            nodes = set()
            for n in find(net, "node"):
                nodes.add((first_val(n, "ref"), first_val(n, "pin")))
            nets[name] = nodes
    return nets


def main():
    if len(sys.argv) > 1:
        path = sys.argv[1]
    else:
        path = os.path.join(tempfile.mkdtemp(), "sd-net.net")
        subprocess.run(
            [KICAD_CLI, "sch", "export", "netlist", "--format", "kicadsexpr",
             "-o", path, SCH],
            check=True, capture_output=True,
        )

    got = parse_netlist(path)
    real = {k: v for k, v in got.items()
            if v and not k.startswith("unconnected-")}

    print("== rev 2.0 netlist vs intent ==\n")
    ok = True
    for name in sorted(set(NETS) | set(real)):
        want = set(NETS.get(name, ()))
        have = real.get(name)
        if have is None:
            print(f"  MISSING  {name}")
            ok = False
        elif not want:
            # PWR_FLAG rides on GND and is not part of the declared netlist.
            if all(r.startswith("#FLG") for r, _ in have):
                continue
            print(f"  EXTRA    {name}: {sorted(have)}")
            ok = False
        else:
            have_real = {p for p in have if not p[0].startswith("#FLG")}
            if have_real != want:
                print(f"  MISMATCH {name}")
                print(f"    missing: {sorted(want - have_real)}")
                print(f"    extra:   {sorted(have_real - want)}")
                ok = False
            else:
                print(f"  ok       {name:<9} {len(want)} nodes")

    print("\n== rev 1.5 -> rev 2.0 connectivity diff ==\n")
    old_of = {}
    for net, members in REV15.items():
        for m in members:
            old_of[m] = net
    new_of = {}
    for net, members in NETS.items():
        for m in members:
            new_of[m] = net

    moved = []
    for node in sorted(set(old_of) | set(new_of)):
        o, n = old_of.get(node), new_of.get(node)
        if o is None:
            moved.append((node, "(unconnected)", n))
        elif n is None:
            moved.append((node, o, "(dropped)"))
    # Group rev 1.5's overloaded net by where each node ended up.
    print("  $1N2351 (the defect) split into:")
    dest = {}
    for node in sorted(REV15["$1N2351"]):
        dest.setdefault(new_of.get(node, "(dropped)"), []).append(node)
    for net in sorted(dest):
        print(f"    {net:<7} <- {' '.join(f'{r}.{p}' for r, p in dest[net])}")
    rev15_refs = {r for members in REV15.values() for r, _ in members}
    added = [(node, n) for node, o, n in moved if o == "(unconnected)"]

    grounded = [(node, n) for node, n in added if node[0] in rev15_refs]
    if grounded:
        print("\n  pads that were floating in rev 1.5, now connected:")
        for node, n in grounded:
            print(f"    {node[0]}.{node[1]:<4} -> {n}")

    new_parts = [(node, n) for node, n in added if node[0] not in rev15_refs]
    if new_parts:
        print("\n  parts added since rev 1.5:")
        for node, n in new_parts:
            print(f"    {node[0]}.{node[1]:<4} -> {n}")
    dropped = [m for m in moved if m[2] == "(dropped)"]
    if dropped:
        print("\n  !! nodes that lost a connection:")
        for node, o, _ in dropped:
            print(f"    {node[0]}.{node[1]} was on {o}")
        ok = False

    print("\n" + ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
